language: java
sudo: false
install: true

jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9

cache:
  directories:
    - "${HOME}/.m2/repository"
    - "${HOME}/.sonar/cache"

notifications:
  email: true
